apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: backstage-demo-service
  description: A small demo service for Backstage GitHub Catalog integration
  annotations:
    github.com/project-slug: sam1607/backstage-demo-service
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest

---

apiVersion: backstage.io/v1alpha1
kind: API

metadata:
  name: artist-api
  description: Retrieve Artist Detail

  annotations:
    github.com/project-slug: sam1607/backstage-demo-service
    backstage.io/techdocs-ref: dir:.

spec:
  type: openapi
  lifecycle: production
  owner: user:default/guest

  definition:
    $text: ./openapi.yaml
