apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo-service
  description: A small demo service for Backstage GitHub Catalog integration
  annotations:
    github.com/project-slug: sam1607/backstage-demo-service

spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
